name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run a simple test
      run: |
        echo "Hello, World!"
        echo "CI is working!"
        
    - name: Check Python
      run: |
        python --version
        
    - name: Success
      run: echo "All checks passed!"
